spring:
    application:
        name: load-tester
    artemis:
        mode: embedded
    jms:
        pub-sub-domain: true
logging:
    level:
      org:
          apache:
              activemq:
                  audit: WARN