spring:
    main:
        banner-mode: off
    application:
        name: load-tester
    artemis:
        mode: native
        broker-url: ${master-address}
    jms:
        pub-sub-domain: true
logging:
    level:
        org:
            apache:
                activemq:
                    audit: WARN